name: javascript
recipe: lamp

services:
  chrome:
    type: compose
    services:
      image: registry.gitlab.com/dmore/docker-chrome-headless:7.2
      command: chromium --headless --remote-debugging-port=9222 --disable-gpu --remote-debugging-address=0.0.0.0 --no-sandbox --disable-dev-shm-usage
      ports:
        - '9222'

tooling:
  behat:
    service: appserver
    cmd: /app/vendor/bin/behat --stop-on-failure
